# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fe0a9a190ec1882c9a1f04bde3e3b08fc9bd5bd2850b814cb45d61b518fbe9edf7d4e63a34198ae149b82bab74e271459aa24cdb4b09897cef29c8044f0b012

test:
  secret_key_base: b53839d710a2c3e15f0972c5bd571a04ba88944c5aa4cdbeb932c1ef660a31bfc92adaa4b0567fbda0965b9c9d46ff81ccc87b5f3ea2c2506d79ba6119bf0c9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
